INSERT INTO Centralina (Nome, xCoordinate, yCoordinate) VALUES ('SMART53', 10.732245000000000, 45.505230000000000);
INSERT INTO Centralina (Nome, xCoordinate, yCoordinate) VALUES ('SMART55', 10.735015000000000, 45.505520000000000);
INSERT INTO Centralina (Nome, xCoordinate, yCoordinate) VALUES ('SMART56', 10.691961666666666, 45.614375000000000);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('RH', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM10', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO2', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM2.5', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('O3', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('VOC', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO_A', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('T', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2_A', 1, 2, 3);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('RH', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM10', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO2', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM2.5', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('O3', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('VOC', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO_A', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('T', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2_A', 1, 2, 4);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('RH', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM10', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO2', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('PM2.5', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('O3', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('VOC', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO_A', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('T', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('CO', 1, 2, 5);
INSERT INTO Sensori (Tipo, Coeff.x1, Coeff.x2, idCantralina) VALUES ('NO2_A', 1, 2, 5);
